### ISSUE TITLE
>component target names should match draw function names

### ISSUE THREAD

**Issue by g-a-v-i-n** [urbit/PaperCollateralRenderer#101]
We have two competing naming schemes for these 'component' functions – one is `_` delimited, and the other is camelCase. I prefer camelCase because its easier to type and read. 

It would be better to stick with one naming scheme going forward. Jimmy is going to re-componentize the wallet designs in Figma, so after that we can get to renaming these.

**Comment by francescanarea** [comment]
sounds good!
