### ISSUE TITLE
Need to add a function that draws a rectangle with filleted corners

### ISSUE THREAD

**Issue by g-a-v-i-n** [urbit/PaperCollateralRenderer#40]
This function should be able to be targeted by the `>` syntax in Figma. It should be written so that it is on the same conceptual level as the items in `js/lib/draw.js`. It will need an entry in `js/lib/draw.js` in the function called `insert()`, and in the `drawLayout` method of PageRenderer where it is actually called.

**Comment by francescanarea** [comment]
@g-a-v-i-n I wasn't able to find any function in this repo named insert.  Is there another function that you meant to describe or were you proposing that the insert function should also be created?

**Comment by g-a-v-i-n** [comment]
Try here https://github.com/urbit/PaperCollateralRenderer/blob/318d71b40c98a584d0725e13d6a36d6df2317488/src/lib/utils.js#L144
