### ISSUE TITLE
`>component` data and draw functions could be generalized

### ISSUE THREAD

**Issue by g-a-v-i-n** [urbit/PaperCollateralRenderer#47]
This is a deeper code clarity issue. The convert() function has bad juju that spreads throughout the library, causing all kinds of complexity to arise, like needing to update `js/lib/utils/insert()`and `/PageRenderer/drawLayout()` every time there is new component. 

It's only job is to convert and simplify the JSON that is returned from the Figma API, but it also needs to detect components with the `>component@data.at.path` syntax. It gets a little complicated partially because we only know the component name at this point, but not the data until a wallet is provided, ie when PaperCollateralRenderer is used in the wild by a user.

- A single source of truth for indexing all `>components`, with a definition for which Figma data they accept. 

I'm imagining a JS object shaped like the following would be one way to start. it could be imported to other files that also need these keys. It would be nice to ditch the ALL_UPPER_CASE_NAMES.
```js
// denote all `>components` like
const FIGMA_ELEMS = {
   patq: 'patq'
   sigil: 'sigil'
   // ...etc
}
```

One would also have to create a standard data format for how `>component` specific data is structured. Now there are [as many types as there are components](https://github.com/urbit/PaperCollateralRenderer/blob/3af3a73d452c6b276192ddf1c8f5c404221aeece/convert.js#L42). There should probably be either one, or a single source of truth for what properties each have.

This way, in `js/lib/utils/insert()` could be a simple function that treats each `>component` data the same way, and `js/PageRenderer/drawLayout could call functions that the data model already knows the name of.`

**Comment by g-a-v-i-n** [comment]
Another thought is that each renderable could be structure like a core in Urbit:
This data model knows the function name it needs to call in order to render itself in the canvas.
```
{
   data: {
      type: 'sigil', 
      size: 64,
      x: 48, 
      y: 280, 
      input: 'ridlur-figbud'
   }
   method: 'draw.sigil'
}
```

**Comment by francescanarea** [comment]
@g-a-v-i-n do we still want to generalize the components?  i implemented this for a second in feat/55 elementSchema.js but it felt clunky because it made it harder to edit what data goes into which type

**Comment by g-a-v-i-n** [comment]
I think we probably do, but I can tackle that in preprocess because there isn't really a notion of 'component' anymore – its handled by the pageSchema.
