### ISSUE TITLE
paths in figma have to be changed to match the extendedWallet

### ISSUE THREAD

**Issue by g-a-v-i-n** [urbit/PaperCollateralRenderer#84]
- right now the paths reference the old transformed wallet, but its better to have them directly match the wallet output.

**Comment by francescanarea** [comment]
@g-a-v-i-n changed all instances of:

- @voting.ethereum.derivationPath --> @meta.derivationPath
- @patp --> @meta.patp
- @ownership.ethereum.address --> @ownership.keys.address
- artboard name "galaxy, master-ticket, 4" --> "galaxy, ticket, 4"

Question:  the shard pages need data from both "ownership" and "shards" within the extendedWallet, so what should the dataPath be for shards?

**Comment by francescanarea** [comment]
branch: [feat/84](https://github.com/urbit/PaperCollateralRenderer/tree/feat/84)

**Comment by g-a-v-i-n** [comment]
Thanks. It looks like this needs to be done for the ownership, spawn, transfer, voting and management paths too. I wrote the correct paths in Figma – do you think you could update the figma layout templates?

The path for shards is just `shards`. Since there are multiple shards, there will prob have to be some step in the preprocess step that generates copies of the page with a single shard each.

**Comment by francescanarea** [comment]
@g-a-v-i-n you meant just re-run convert so that templates.json is updated right?

**Comment by g-a-v-i-n** [comment]
@francescanarea, the actual element titles in figma need to be updated.

**Comment by francescanarea** [comment]
@g-a-v-i-n I believe that I did that a few days ago?  by "all instances" i meant for each type of component/each page (apologies if this was vague).  

just wanted to check that the data for the master ticket component is just [@ticket](https://github.com/urbit/PaperCollateralRenderer/blob/a58efbc0ff53712aae20322d9e1eaf41ebe27698/preview/dist/js/sampleWallets/wallet0.json#L10)

<img width="273" alt="Screen Shot 2019-08-15 at 1 14 12 PM" src="https://user-images.githubusercontent.com/7469427/63123765-9b02e500-bf5e-11e9-99c6-2560e88c802f.png">

**Comment by francescanarea** [comment]
@g-a-v-i-n deleted my previous comment because went back to do an in-depth check.  it looks like i made the changes.  wanted to check in to ask if network will have a similar structure to every other template (like voting and management) since wallet0's was null

**Comment by g-a-v-i-n** [comment]
@francescanarea no need to do anything with networking keys for now

**Comment by francescanarea** [comment]
@g-a-v-i-n network === multipass?

**Comment by g-a-v-i-n** [comment]
The network keys are normally pretty hidden from the user, because the management proxy is used to generate + regenerate them. The keys themselves are 1 pair of authentication keys and 1 pair of encryption keys, both pairs used for networking. The keys are in a file, which gets loaded into Arvo to start and use a ship.
