### ISSUE TITLE
tools/convert.js could have a figma img --> base64 encoding func

### ISSUE THREAD

**Issue by francescanarea** [urbit/PaperCollateralRenderer#85]
For non-special images, such as the key icon, we manually downloaded this image from figma, converted this to base64 using a random website, then hard-coded @keyIcon to be rendered using the copied and pasted base64 string.  

However, we could probably create a function in convert that makes an http req to the images used in our figma (via the figma api).  We could then do our own base64 encoding.  

Not sure if this is worth it/fully possible but just a passing thought I had.

**Comment by g-a-v-i-n** [comment]
There are a couple of options here:

- Make a bash script in package.json that just uses the systems `base64` command
- Make a node script that does basically the same thing
- mark the icon in figma with `>` syntax, get the path data from the Figma JSON, convert to SVG, and then base64 encode.

Leaving it up to you if you want to do this and how.
