### ISSUE TITLE
Removing "custody" folders

### ISSUE THREAD

**Issue by jyng** [urbit/PaperCollateralRenderer#86]
Could we remove the custody folders that get outputted? In the new design, the custody recommendations are included inside the respective paper wallet.

**Comment by jyng** [comment]
<img width="355" alt="Screen Shot 2019-08-14 at 10 54 34 AM" src="https://user-images.githubusercontent.com/9557907/63043884-f612da00-be81-11e9-99d1-1a136aede8fd.png">

**Comment by francescanarea** [comment]
@g-a-v-i-n where does the bundling happen? is it in this lib (i'd be surprised since i haven't yet come across this part) or somewhere else?

**Comment by g-a-v-i-n** [comment]
You're correct, the binning happened in the wallet generator webapp. PCR just returns an array of pages with metadata (incl bin target) attached.

**Comment by g-a-v-i-n** [comment]
@jyng gonna close this bc it should be handled in Bridge
